[package]
name = "country_geocoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cities-json = "0.5.5"
geometry-rs = "0.2.1"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
